# Generated by Django 3.0.5 on 2020-04-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200422_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cover_image',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
